modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/bedrock_destroyer/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "bedrock_destroyer"
version = "${version}"
displayName = "Bedrock Destroyer"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.bedrock_destroyer]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bedrock_destroyer]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
